# Generated by Django 3.1.5 on 2021-01-19 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='Null', max_length=255, verbose_name='Город')),
                ('city_name_in_url', models.CharField(max_length=255, null=True, verbose_name='Город в ссылке на авито')),
                ('category_parsing', models.SmallIntegerField(default=5, max_length=255, null=True, verbose_name='Категория города по размеру')),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 7, 13, 12, 20485), verbose_name='Дата парсинга информации')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautybox.region')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 7, 13, 12, 20831), verbose_name='Дата парсинга информации')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('created', models.CharField(max_length=255, verbose_name='Дата создания')),
                ('owner_info', models.CharField(max_length=1000, verbose_name='Информация о владельце')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Контактное лицо')),
                ('address', models.CharField(max_length=1000, verbose_name='Адрес')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('url', models.CharField(max_length=1000, verbose_name='Ссылка')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautybox.region')),
            ],
        ),
    ]
