# Generated by Django 3.1.5 on 2021-01-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beautybox', '0002_auto_20210119_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='city_name_in_url',
            new_name='region_name_in_url',
        ),
        migrations.RemoveField(
            model_name='region',
            name='city_name',
        ),
        migrations.AddField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='url',
            name='region_name',
            field=models.CharField(default=None, max_length=255, verbose_name='Название города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='url',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautybox.region'),
        ),
    ]
