# Generated by Django 3.1.5 on 2021-01-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautybox', '0004_auto_20210120_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=1000, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
