# Generated by Django 3.1.5 on 2021-01-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautybox', '0005_auto_20210120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='parsing_status',
            field=models.SmallIntegerField(default=2, verbose_name='Статус парсинга'),
        ),
    ]
